apiVersion: v1
kind: ReplicationController
metadata:
  name: file
  namespace: grouk
  labels:
    name: file
spec:
  replicas: 1
  selector:
    name: file
  template:
    metadata:
      labels:
        name: file
    spec:
      containers:
      - name: file
        image: harbor.tiejin.cn/closer/umscloud-fileserver:latest
        env:
        - name: UMSCLOUD_FILESERVER_OPTS
          value: -Denv=test -Dserver_id=grouk_file_server_0 -Dserver_num=0 -Dumscloud_outerip=api.demo.grouk.io -Ddomain=grouk -DpublicApiHost=http://api.demo.grouk.io -DpublicFileHost=http://file.demo.grouk.io -DwebHost=http://web.demo.grouk.io
        ports:
        - containerPort: 2080
        imagePullPolicy: IfNotPresent

  restartPolicy: Always
