apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  namespace: grouk
  labels:
    name: elasticsearch
spec:
  replicas: 1
  selector:
    name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: harbor.tiejin.cn/closer/umscloud-elasticsearch:latest
        args:
        - --cluster.name=grouk_es
        ports:
        - containerPort: 9200
        - containerPort: 9300
        imagePullPolicy: IfNotPresent

  restartPolicy: Always
