apiVersion: v1
kind: ReplicationController
metadata:
  name: api
  namespace: grouk
  labels:
    name: api
spec:
  replicas: 1
  selector:
    name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: harbor.tiejin.cn/closer/umscloud-server:latest
        env:
        - name: UMSCLOUD_SERVER_OPTS
          value: -Denv=test -Dserver_id=grouk_api_server_0 -Dserver_num=0 -Dumscloud_outerip=api.demo.grouk.io -Ddomain=grouk -DpublicApiHost=http://api.demo.grouk.io -DpublicFileHost=http://file.demo.grouk.io -DwebHost=http://web.demo.grouk.io
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8082
        - containerPort: 8088
        imagePullPolicy: IfNotPresent

  restartPolicy: Always
