apiVersion: v1
kind: Pod
metadata:
  name: grouk-tools
  namespace: grouk
spec:
  containers:
  - image: harbor.tiejin.cn/closer/grouk-tools
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: grouk-tools
  restartPolicy: Always
