apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: grouk
  labels:
    name: mysql-slave
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    # current use master as slave
    name: mysql-master
