apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: grouk
  labels:
    name: elasticsearch
spec:
  ports:
    # the port that this service should serve on
  - port: 9300
    name: "api"
    targetPort: 9300
  - port: 9200
    name: "manager"
    targetPort: 9200
  selector:
    name: elasticsearch

  clusterIP:  10.254.2.15
