apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: grouk
  labels:
    name: api
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: "http"
    targetPort: 8080
  - port: 8081
    name: "gw"
    targetPort: 8081
  - port: 8082
    name: "rpc"
    targetPort: 8082
  - port: 8088
    name: "websocket"
    targetPort: 8088

  selector:
    name: api

#  type: NodePort
  clusterIP:  10.254.2.10
