apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
  namespace: grouk
  labels:
    name: mongo
spec:
  replicas: 1
  selector:
    name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: harbor.tiejin.cn/closer/mongo:3.0
        ports:
        - containerPort: 27017
        imagePullPolicy: IfNotPresent

  restartPolicy: Always
