apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: grouk
  labels:
    name: web
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: "http"
    targetPort: 80

  selector:
    name: web

#  type: NodePort
  clusterIP:  10.254.2.11
