apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: grouk
  labels:
    name: search
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: "http"
    targetPort: 6666

  selector:
    name: search

#  type: NodePort
  clusterIP:  10.254.2.13
