apiVersion: v1
kind: Service
metadata:
  name: fetch
  namespace: grouk
  labels:
    name: fetch
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: "http"
    targetPort: 6789

  selector:
    name: fetch

#  type: NodePort
  clusterIP:  10.254.2.14
